// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mutual_information
double mutual_information(arma::mat joint_dist);
RcppExport SEXP _pacote5_mutual_information(SEXP joint_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type joint_dist(joint_distSEXP);
    rcpp_result_gen = Rcpp::wrap(mutual_information(joint_dist));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP exp_smooth_c(void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_pacote5_mutual_information", (DL_FUNC) &_pacote5_mutual_information, 1},
    {"exp_smooth_c", (DL_FUNC) &exp_smooth_c, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_pacote5(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
