# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate the mutual information
#'
#' @description
#' Calculate the mutual information
#'
#' @param joint_dist A numeric matrix
#' @return The mutual information
#' @useDynLib pacote5, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
mutual_information <- function(joint_dist) {
    .Call(`_pacote5_mutual_information`, joint_dist)
}

